# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      build_timestamp:
        enabled: true

builders:
  build_timestamp:
    import: "package:build_timestamp/builder.dart"
    builder_factories: ["buildTimestamp"]
    build_extensions: {"pubspec.yaml": ["lib/src/timestamp.dart"]}
    defaults:
      options:
        output: "lib/src/timestamp.dart"
    build_to: source
    auto_apply: dependents
