name: build_timestamp
description: A builder for generating the build_runner's timestamp into code.
version: 0.1.0
repository: https://github.com/Praxa-Sense/build_timestamp

environment:
  sdk: ^3.0.0

dependencies:
  build: ^2.1.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_verify: '>=2.0.0 <4.0.0'
  checked_yaml: ^2.0.0
  dart_flutter_team_lints: ^1.0.0
  test: ^1.2.0
